/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface Todo {
  completed: boolean;
  description: string;
  id?: number;
  title?: string;
}
