/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface TodoResponse {
  completed: boolean;
  id: number;
  title: string;
}
