/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface User {
  email?: string;
  id?: number;
  name?: string;
  password?: string;
}
